### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Fix half the misspellings with [`typos`](https://github.com/crate-ci/typos).

I took the liberty to rename `$unit_espace = '&nbsp;';` to `$unit_nbspace` leaving [espace to Renault](https://fr.wikipedia.org/wiki/Renault_Espace) :)

`.typos.toml`

```toml
[files]
extend-exclude = [
    "public/css/",
    "public/font/",
    "public/js/"
]
[default.extend-identifiers]
"ND" = "ND"
"WeeWX" = "WeeWX"
"Wordpress" = "WordPress"
[default.extend-words]
# The other half to fix
"datas" = "datas"
"informations" = "informations"
"serie" = "serie"
```

Please consider renaming: datas, informations, serie - these are not in English.
You may also like https://github.com/szepeviktor/uninformative-words

### CODE REVIEW

**Comment by jaz-on** [comment]
Thanks @szepeviktor for the PR. I didn't know about [crate-ci/typos](https://github.com/crate-ci/typos) and [your little repo](https://github.com/szepeviktor/uninformative-words), II appreciate it.

I'll dig into it and learn how to apply it to this project, it's going to be very useful when it comes to checking simple mistakes.

May I ask you how you ended up reviewing the Weather Station plugin repo? :)

**Comment by szepeviktor** [comment]
> how you ended up reviewing the Weather Station plugin repo? :)

This way

image

**Comment by szepeviktor** [comment]
> Please consider renaming: datas, informations, serie - these are not in English.

The next step could be.

https://github.com/search?q=repo%3AWeather-Station-Software%2Flive-weather-station%20%22informations%22&type=code

> In English, "information" is an uncountable [mass noun](https://en.wikipedia.org/wiki/Mass_noun).

**Comment by jaz-on** [comment]
Pierre, the original developer, and I are French.

As these words are also used in French (and countable in our mother language), we made mistakes when naming parts of the codebase...

I'll work on it and be way more strict on the naming convention in the future thanks for the heads-up!😉

**Comment by szepeviktor** [comment]
ChatGPT agrees!

image

**Pull request merged**
